name: hello workflow
#Run on the trigger
on: 
  push:
      branches: [main]
jobs:
    greet:
      runs-on: ubuntu-latest
      steps:
      
        - name: say hello to user
          run: echo "Hello dosto"

        - name:  hello to username 
          run: echo "hello $USER" 

    details:                   
      runs-on: ubuntu-latest
      steps:
        - name: versions of python, docker, etc
          run: docker --version && Pyhton --version 
