name: hello workflow
#Run on the trigger
on: 
  push:
      branches: [main]
jobs:
    greet:
      runs-on: ubuntu-latest
      steps:
      
        - name: hello dosto
          run: echo "Hello dosto"

        - name: say hello to username 
          run: echo "hello $USER" 
