name: Porfolio

on:
  push:
    branches: [main]
    #workflow_dispatch:

 permissions:
      pages: write
      id-token: write

job:
  deploy:
    runs-on: ubuntu-latets

         environment:
            name: github-pages
            url: ${{ steps.deployment.outputs.page_url }} 

    steps:
      # This action checks-out your repository under $GITHUB_WORKSPACE, so your workflow can access it.
      - name: checkout code
        uses: actions/checkout@v4
      # A GitHub Action to enable Pages and extract various metadata about a site. It can also be used to configure various static site generators we support as starter workflows.
      - name: Setup GitHub Pages
        uses: action/configure-pages@v4

      # static code artifacts pages
      - name: Upload static files
        uses: action/upload-pages-artifact@v4

      - name: Deploy to Github pages
        uses: action/deploy-pages@v4
